[package]
name = "bridge-loader"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.5.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
winres = "0.1.8"