[package]
name = "bridge-types"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
bridge-value = { path = "../bridge-value" }
bridge-derive = { path = "../bridge-derive" }